# Generated by Django 6.0.2 on 2026-03-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dare_image',
            field=models.ImageField(blank=True, null=True, upload_to='dare_image/'),
        ),
    ]
