# Generated by Django 6.0.2 on 2026-03-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_dare_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dare_image',
            new_name='image',
        ),
    ]
